---
# First execute the 10-boostrap.yml file, then run this file.
- hosts: all
  become: true 
 
  pre_tasks:
  - name: Update repository cache in Ubuntu
    tags: always
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
     
  - name: Update repository cache in CentOS
    tags: always
    dnf:
      update_cache: yes
    when: ansible_distribution == "CentOS" 
    
# The "change_when" attribute is used to control when a task is marked as "changed" during playbook execution.
# By default, Ansible marks a task as "changed" if any changes are made on the target system, such as installing a package, modifying a file, or restarting a service.
# Here we don't want this task to be marked as "changed"

# - hosts: web_servers
#   become: true
#   tasks:  
#   - name: Install apache and php packages for Ubuntu
#     tags: ubuntu,apache
#     apt:   
#       name:
#        - apache2
#        - libapache2-mod-php
#       state: latest
#     when: ansible_distribution == "Ubuntu"
      
#   - name: Install apache and php packages for CentOS
#     tags: centos,apache
#     dnf:
#       name:
#         - httpd
#         - php
#       state: latest
#     when: ansible_distribution == "CentOS"
 
#   - name: Copying website file in Web Server
#     tags: ubuntu,centos,apache
#     copy:
#       src: ./files/index.html
#       dest: /var/www/html/index.html
#       owner: root
#       group: root
#       mode: 0644


#   - name: Starting httpd service in CentOS
#     tags: centos,apache,httpd
#     service:
#       name: httpd
#       state: started
#       enabled: yes
#     when: ansible_distribution == "CentOS"
    
    
#   - name: Allowing communication on port 80 in CentOS
#     tags: centos,httpd
#     shell: firewall-cmd --add-port=80/tcp
#     when: ansible_distribution == "CentOS"       
 

#   - name: Change the ServerAdmin email in apache config file in CentOS
#     tags: centos,httpd,apache
#     lineinfile:
#       path: /etc/httpd/conf/httpd.conf      
#       regexp: "^ServerAdmin"      
#       line: "ServerAdmin ahmadshoaibjoya@gmail.com"
#     when: ansible_distribution == "CentOS"
#     register: myoutput  
  
#   - name: Restart apache (httpd) service in CentOS
#     tags: centos,httpd,apache
#     service:
#       name: httpd
#       state: restarted
#     when: myoutput.changed  
 
