---

- hosts: all
  become: true
  
  tasks:
  
  - name: Install apache and php packages for Ubuntu
    apt:
      update_cache: yes
# Here we list packages in one task      
      name:
       - apache2
       - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"
    
    
  - name: Install apache and php packages for CentOS
    dnf:
      update_cache: yes
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"
