  # This playbook uses our host variables which are defined in host_vars folder: apache_package_name, php_package_name, apache_service. 
  # This playbook is for both Ubuntu and CentOS
  - name: Install apache and php packages
    tags: ubuntu,centos,apache,httpd
    # We use "package" module because it is generic package manager. This task is for both Ubuntu and CentOS
    package:
      name:
       - "{{ apache_package_name }}"
       - "{{ php_package_name }}"
      state: latest


  - name: Starting and enabling apache service
    tags: centos,apache,httpd
    service:
      name: "{{ apache_service }}"
      state: started
      enabled: yes

    
  - name: Allowing communication on port 80
    tags: centos,httpd
    shell: firewall-cmd --add-port=80/tcp
    when: ansible_distribution == "CentOS"       
 
  - name: Change the ServerAdmin email in apache config file
    tags: centos,httpd,apache
    lineinfile:
      path: /etc/httpd/conf/httpd.conf      
      regexp: "^ServerAdmin"    
      line: "ServerAdmin myemail@gmail.com"
    when: ansible_distribution == "CentOS"
    notify: restart_apache
  # The "notify" specifies Handler to be triggered,
  # and "restart_apache" is our created hander name.
  # We defined the hander in the handlers folder.



  - name: Copying website file in Web Server
    tags: ubuntu,centos,apache
    copy:
      src: ./files/index.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

